modLoader="javafml"
loaderVersion="[${loader_version},)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/RuneCraftory/issues"
[[mods]]
modId="runecraftory"
version="${version}"
displayName="RuneCraftory"
displayURL="https://www.curseforge.com/minecraft/mc-mods/runecraftory"
logoFile="icon.png"
authors="Flemmli97"
description='''A minecrafty Harvest Moon'''
[[dependencies.runecraftory]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="tenshilib"
mandatory=true
versionRange="[${tenshilib_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="simplequests"
mandatory=false
versionRange="[1.18.2-1.3.1,)"
ordering="NONE"
