modLoader="javafml"
loaderVersion="[${loader_version},)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/RuneCraftory/issues"
[[mods]]
modId="runecraftory"
version="${version}"
displayName="RuneCraftory"
displayURL="${homepage}"
logoFile="logo.png"
authors="Flemmli97"
description='''A minecrafty Harvest Moon'''
[[dependencies.runecraftory]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="tenshilib"
mandatory=true
versionRange="[${tenshilib_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.runecraftory]]
modId="simplequests"
mandatory=false
versionRange="[${simplequest_api_version},)"
ordering="NONE"
