apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/fabric.gradle"

loom {
    accessWidenerPath.set file("src/main/resources/runecraftory.accesswidener")
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
    mod_meta.forge_config_api = forge_config_api
    mod_meta.sbl_version = sbl_version
}

repositories {
    maven { url "https://maven.terraformersmc.com/releases/" }
    maven {
        name = "CurseMaven"
        url "https://www.cursemaven.com"
    }
}

dependencies {
    modImplementation "io.github.flemmli97:tenshilib:${tenshilib_version}-fabric"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api}"
    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${minecraft_version}:${sbl_version}"

    modRuntimeOnly include("io.github.flemmli97:simplequests_api:${simplequests_api_version}-fabric") {
        transitive = false
    }
    // Jar-Jar not added otherwise
    modRuntimeOnly "io.github.flemmli97:lingua_bib:${lingua_bib}-fabric"

//    modRuntimeOnly "mezz.jei:jei-1.21.1-fabric:${jei_version}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    modRuntimeOnly "maven.modrinth:jade:${jade_fabric}"
    modRuntimeOnly "net.favouriteless.modopedia:modopedia-fabric-${minecraft_version}:${modopedia}"

    modRuntimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.8-fabric"
}