org.gradle.jvmargs=-Xmx3G
enabled_platforms=fabric,neoforge
minecraft_version=1.21.1
neoForm_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
# NeoForge Properties
neo_loader_version=2
neoforge_version=21.1.196
# Fabric Properties
fabric_loader_version=0.16.14

# Mod Properties
mod_version=2.2.0
maven_group=io.github.flemmli97
mod_id=runecraftory
mod_author=flemmli97

# Dependencies
fabric_version=0.116.4+1.21.1
tenshilib_version=1.21.1-2.3.0
simplequests_api_version=1.21.1-2.1.0
lingua_bib=1.21.1-1.0.5
sbl_version=1.16.11
forge_config_api=21.1.3
jei_version=19.9.1.125
rei_version=16.0.799
jade_fabric=aYVY3zTC
jade_neoforge=43sRR8f6
top_version=1.21_neo-12.0.4-6
modopedia=1.1.5
seasons_neoforge=SPj5bJoM
minecolonies=1.1.1036-1.21.1-snapshot

# Curse properties
curse_versions=1.21.1, Java 21
curse_page_fabric=https://www.curseforge.com/minecraft/mc-mods/runecraftory
curse_id_fabric=292745
curse_dep_fabric=fabric-api, tenshilib-fabric, smartbrainlib, forge-config-api-port
optional_curse_dep_fabric=modopedia
curse_page_forge=https://www.curseforge.com/minecraft/mc-mods/runecraftory
curse_id_forge=292745
curse_dep_forge=tenshilib, smartbrainlib
optional_curse_dep_forge=modopedia
modrinth_versions=1.21.1
modrinth_page=https://modrinth.com/mod/runecraftory
modrinth_id=m7U2nGaM
modrinth_dep_fabric=fabric-api, tenshilib, smartbrainlib, forge-config-api-port
optional_modrinth_dep_fabric=modopedia
modrinth_dep_forge=tenshilib, smartbrainlib
optional_modrinth_dep_forge=modopedia

# Other
project_name=RuneCraftory
full_changelog=https://github.com/Flemmli97/RuneCraftory/blob/1.21.1/Changelog.md
discord_role=852113519305687061
