modLoader="javafml"
loaderVersion="[28,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Flemmli97/FateUBW/issues"
displayURL="https://github.com/Flemmli97/FateUBW"
# logoFile=""
credits=""
authors="Flemmli97"
[[mods]] 
  modId="runecraftory"
  version="${file.jarVersion}"
  displayName="RuneCraftory"
  # updateJSONURL=""
  authors="Flemmli97"
  description='''A minecrafty Harvest Moon'''
[[dependency.runecraftory]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.3]"
  ordering="NONE"
  side="BOTH"
[[dependencies.improvedmobs]]
  modId="tenshilib"
  mandatory=true
  versionRange="[1.3.1,)"
  ordering="AFTER"
  side="BOTH"
