plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

dependencies {
    implementation "io.github.flemmli97:tenshilib:${tenshilib_version}-common"
    implementation("io.github.flemmli97:simplequests_api:${simplequests_api_version}-common") {
        transitive = false
    }
    implementation "net.tslat.smartbrainlib:SmartBrainLib-common-${minecraft_version}:${sbl_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api}"

    commonDependency("mezz.jei:jei-1.21.1-neoforge:${jei_version}")
    commonDependency("me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}")
    commonDependency("me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei_version}")
    commonDependency("maven.modrinth:jade:${jade_neoforge}")
    commonDependency("maven.modrinth:serene-seasons:${seasons_neoforge}")
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}